In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import generic_filter
from skimage.morphology import medial_axis

In [12]:
cleaned_intersections = pd.read_csv('/Users/bendevlin/Desktop/completed_mgla_testing/sholl_output/cleaned_intersections.csv', index_col = 0)

In [13]:
def dist_formula(x1, y1, x2, y2):
    import numpy as np

    d = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

    return d

In [9]:
for cur in cleaned_intersections.iterrows():
    for new in cleaned_intersections.iterrows():
        if dist_formula(cur[1][0], cur[1][1], new[1][0], new[1][1]) < 10:
        ## and now to set the new index values equal to the current index values
            cleaned_intersections.loc[new[0]] = cleaned_intersections.loc[cur[0]]

    ##if they are within a certain distance of one another, make them duplicates
    ##which we can then remove using pandas

## using pandas to drop any duplicates
final_intersections = cleaned_intersections.drop_duplicates()

In [21]:
cleaned_intersections

0      1
0    351.0  369.0
1    351.0  369.0
2    351.0  370.0
3    352.0  368.0
4    353.0  367.0
..     ...    ...
587  632.0  500.0
588  632.0  501.0
589  641.0  527.0
590  642.0  525.0
591  642.0  526.0

[592 rows x 2 columns]

In [19]:
z = pd.read_csv('/Users/bendevlin/Desktop/completed_mgla_testing/sholl_output/testing.csv', index_col = 0)

In [45]:
z

0      1      2      3      4      5      6      7      8      9  \
5    349.0  369.0  350.0  368.0  351.0  367.0  352.0  367.0  353.0  367.0   
25   332.0  358.0  332.0  359.0  333.0  357.0  334.0  356.0  335.0  355.0   
45   314.0  349.0  315.0  348.0  316.0  346.0  316.0  347.0  317.0  345.0   
65   303.0  330.0  304.0  329.0  305.0  328.0  310.0  421.0  311.0  422.0   
85   289.0  316.0  290.0  315.0  291.0  314.0  292.0  313.0  293.0  312.0   
105  265.0  314.0  266.0  313.0  267.0  312.0  268.0  310.0  268.0  311.0   
125  246.0  307.0  247.0  305.0  247.0  306.0  248.0  304.0  263.0  459.0   
145  223.0  307.0  223.0  308.0  224.0  305.0  224.0  306.0  225.0  304.0   
165  201.0  307.0  202.0  305.0  202.0  306.0  203.0  303.0  203.0  304.0   
185  179.0  308.0  179.0  309.0  179.0  310.0  180.0  306.0  180.0  307.0   
205  158.0  308.0  158.0  309.0  159.0  305.0  159.0  306.0  159.0  307.0   
225  131.0  333.0  131.0  334.0  132.0  329.0  132.0  330.0  132.0  331.0   
245  108.0  357.0  108.0  358.0  108.0  359.0  109.0  349.0  109.0  350.0   
265  260.0  620.0  261.0  621.0  262.0  621.0  263.0  621.0  264.0  622.0   
285  604.0  507.0  605.0  505.0  605.0  506.0  608.0  499.0  609.0  497.0   
305  627.0  505.0  627.0  506.0  628.0  503.0  628.0  504.0  629.0  501.0   
325  639.0  526.0  640.0  524.0  640.0  525.0  641.0  523.0    NaN    NaN   
345    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

     ...    172    173    174    175    176    177    178    179    180    181  
5    ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
25   ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
45   ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
65   ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
85   ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
105  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
125  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
145  ...  498.0  380.0  498.0  381.0  498.0  382.0  498.0  383.0  498.0  384.0  
165  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
185  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
205  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
225  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
245  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
265  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
285  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
305  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
325  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
345  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  

[18 rows x 182 columns]

In [33]:
## function for separating an array of numbers into x, y coordinates

def x_y_separate(arr):
    
    xs = []
    ys = []

    pairs = zip(arr[::2], arr[1::2])
    for inter in list(pairs):
        xs = np.append(xs, inter[0])
        ys = np.append(ys, inter[1])

    x, y = xs, ys
    
    return x, y

In [68]:
## this is cleaning the intersections and saving the intersections
## we will do this individually for each image
## input is 'z' which is the output from the current calc_intersections fxn

intersections_to_plot = pd.DataFrame()

for idx, row in z.iterrows():
    
    vals = row.dropna().values
    
    x, y = x_y_separate(vals)   
    
    cleaned_intersections = pd.DataFrame(pd.DataFrame([x, y]).T)

    for cur in cleaned_intersections.iterrows():
        for new in cleaned_intersections.iterrows():
            if dist_formula(cur[1][0], cur[1][1], new[1][0], new[1][1]) < 10:
            ## and now to set the new index values equal to the current index values
                cleaned_intersections.loc[new[0]] = cleaned_intersections.loc[cur[0]]
     
    ## dropping the duplicates
    final_intersections = cleaned_intersections.drop_duplicates()
    final_intersections['ring'] = idx
    final_intersections.set_index('ring', inplace = True)
    
    ## saving the intersection x and y values to be plotted
    intersections_to_plot = intersections_to_plot.append(final_intersections)

<ipython-input-68-329d44b3273a>:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_intersections['ring'] = idx


In [75]:
pd.DataFrame(np.unique(intersections_to_plot.index, return_counts = True))

0   1   2   3   4    5    6    7    8    9    10   11   12   13   14   15  \
0   5  25  45  65  85  105  125  145  165  185  205  225  245  265  285  305   
1   2   3   6   4   5    9   10   14   10    9   15   10    6    6    3    2   

    16  
0  325  
1    1

In [91]:
### okay now i want to see if i can calculate # of endpoints from the skeleton easily

skeleton = pd.read_csv('/Users/bendevlin/Desktop/completed_mgla_testing/sholl_output/skeleton.csv', index_col = 0)

In [92]:
# Line ends filter
def num_endpoints(P):
    """Central pixel and just one other must be set to be a line end"""
    return 255 * ((P[4]==255) and np.sum(P)==510)

In [93]:
# Find line ends
result = generic_filter(skeleton, lineEnds, (3, 3))

In [99]:
np.unique(result, return_counts = True)

(array([  0., 255.]), array([562471,     29]))

In [95]:
def calc_intersection(circ_arr, skeleton_arr):
    intersects = []

    for i in range(len(circ_arr)):
        for j in range(len(mgla_arr)):
            if circ_arr[i][j] == skeleton_arr[i][j]:
                intersects = np.append(intersects, [i, j])

    return(intersects)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [100]:
ep = []

for i in range(len(result)):
    for j in range(len(result)):
        if result[i][j] == 255.0:
            ep = np.append(ep, [i, j])
            

In [101]:
ep

array([100., 389., 144., 298., 152., 484., 153., 521., 171., 490., 197.,
       239., 265., 220., 265., 625., 282., 574., 316., 606., 326., 336.,
       340., 424., 374., 273., 375., 262., 379., 131., 382., 228., 401.,
       111., 408., 281., 448., 160., 474., 352., 481., 400., 503., 363.,
       529., 185., 538., 511., 551., 180., 558., 426., 577., 498., 608.,
       510., 644., 528.])

In [102]:
x_y_separate(ep)

(array([100., 144., 152., 153., 171., 197., 265., 265., 282., 316., 326.,
        340., 374., 375., 379., 382., 401., 408., 448., 474., 481., 503.,
        529., 538., 551., 558., 577., 608., 644.]),
 array([389., 298., 484., 521., 490., 239., 220., 625., 574., 606., 336.,
        424., 273., 262., 131., 228., 111., 281., 160., 352., 400., 363.,
        185., 511., 180., 426., 498., 510., 528.]))